site_name: Mudslinger Docs
markdown_extensions:
    - codehilite
theme: readthedocs
# site_url: https://mudslinger.net
repo_url: https://github.com/rabidt/mudslinger
docs_dir: userdocs
site_dir: browser/static/docs

nav:
    - 'Mudslinger Home': '/'
    - 'Docs Home': 'README.md'
    - 'Scripting API': 'scripting.md'
